Adjust sha1_random_uuid usage in jabber/conference.c
The jabber/conference.c module failed to compile due to the implicit use
of the sha1_random_uuid function following the deprecation of the sha1
lib. This patch reintroduces the sha1.h include to resolve compilation
errors encountered with GCC 14:

  error: implicit declaration of function ‘sha1_random_uuid’

Additionally, the patch corrects the type mismatch error when calling
sha1_random_uuid, aligning with the expected ‘GChecksum **’ type,
otherwise compilation fails with following error:

  error: passing argument 1 of ‘sha1_random_uuid’ from incompatible pointer type
  note: expected ‘GChecksum **’ {aka ‘struct _GChecksum **’} but argument is of type ‘GChecksum *’ {aka ‘struct _GChecksum *’}

Fixes: a4ac9c413b97 ("Deprecate sha1_* functions (#172)")